#!/bin/bash

EXECUTABLE=./assembler

cp -r /autograder/submission/* /autograder/source/

pushd /autograder/source/ >/dev/null

# remove any hack or asm files in submission and copy test asm files over
rm -f *.asm *.hack
cp /autograder/grader/tests/*.asm .

# run student-submitted setup script (untrusted)
chmod +x ./setup.sh
runuser -u student -- ./setup.sh

# in case setup.sh created hack files
rm -f *.hack

# run student-submitted code (untrusted)
chmod ugo+x "${EXECUTABLE}"

popd >/dev/null

# diff outputs with expected
cd /autograder/grader
uv run src/run_tests.py
