#!/bin/bash

EXECUTABLE=./Assembler

SUBMISSION_DIR=$(realpath $(dirname $(find -name 'setup.sh' -type f)))
cp -r ${SUBMISSION_DIR}/* /autograder/source/

pushd /autograder/source/ >/dev/null

# remove any hack or asm files in submission
rm -f *.asm *.hack

# run student-submitted setup script (untrusted)
chmod +x ./setup.sh
runuser -u student -- ./setup.sh

# in case setup.sh created hack files
rm -f *.hack

# copy test files over
cp /autograder/grader/tests/*.asm .

chmod ugo+x "${EXECUTABLE}"

popd >/dev/null

# diff outputs with expected
cd /autograder/grader
uv run src/run_tests.py
