#!/bin/bash

EXECUTABLE=./assembler

cd /autograder/grader
mkdir /autograder/results
mkdir /autograder/outputs
mkdir /autograder/source

chmod o= /autograder/submission
chmod o= /autograder/results
chmod o= /autograder/outputs
chmod +rwx /autograder/source

cp /autograder/submission/ /autograder/source/

pushd /autograder/source/

# remove any hack or asm files in submission and copy test asm files over
rm *.asm *.hack
cp /autograder/grader/tests/*.asm .

# run student-submitted setup script (untrusted)
chmod +x ./setup.sh
runuser -u student -- ./setup.sh

# in case setup.sh created hack files
rm *.hack

# run student-submitted code (untrusted)
chmod +x "${EXECUTABLE}"
runuser -u student -- ls *.asm | xargs -I{} ${EXECUTABLE} $(pwd)/{}

# copy outputs to own directory
mv *.hack /autograder/outputs

popd

# diff outputs with expected
uv run src/run_tests.py
